MVCC.Website/Models/AppointmentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MVCC.Model.Entities;

namespace MVCC.Website.Models
{
    public class AppointmentViewModel
    {
        public IEnumerable<Appointment> Appointments { get; set; }
    }

    public class AppointmentSetDateViewModel
    {
        public Guid Id { get; set; }
        public DateTime Date { get; set; }
        public DateTime Time { get; set; }
    }

}

MVCC.Website/Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCC.Data.Repositories;
using MVCC.Web.Shared.Extensions;
using MVCC.Website.Models;
using PagedList;

namespace MVCC.Website.Controllers
{
    public class AppointmentController : Controller
    {
        private AppointmentRepository _appointmentRepository;

        public AppointmentController(AppointmentRepository appointmentRepository)
        {
            _appointmentRepository = appointmentRepository;
        }

        // GET: Appointment
        public ActionResult Index(int page = 1)
        {


            var model = new AppointmentViewModel();
            var list =
                _appointmentRepository.GetByDoctor(HttpContext.User.Identity.GetGuidUserId(), page)
                    .ToPagedList(page, 20);
            model.Appointments = list;
            return View(model);
        }

        public ActionResult Approve(Guid id)
        {
            try
            {
                var x = _appointmentRepository.Approve(id);
                if (x)
                {
                    TempData["Message"] = "Success";
                    return RedirectToAction("Index");
                }
                TempData["Message"] = "Error";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["Message"] = "Error";
                return RedirectToAction("Index");
            }
        }




        [HttpGet]
        public ActionResult SetDate(Guid id)
        {
            try
            {
                var models = _appointmentRepository.GetById(id);
                if (models != null)
                {
                    var model = new AppointmentSetDateViewModel()
                    {
                        Date = models.AppointmentDate,
                        Id = models.Id
                    };
                    return View(model);
                }
                TempData["Message"] = "Error";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["Message"] = "Error";
                return RedirectToAction("Index");

            }
        }

        public ActionResult Delete(Guid id)
        {
            try
            {
                _appointmentRepository.Delete(p => p.Id == id);
                TempData["Message"] = "Success";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult SetDate(AppointmentSetDateViewModel model)
        {
            try
            {
                var x = _appointmentRepository.Approve(model.Id, model.Date.Add(model.Time.TimeOfDay));
                if (x)
                    return RedirectToAction("Index");
                TempData["Message"] = "Error";
                return RedirectToAction("Index");

            }
            catch (Exception)
            {
                TempData["Message"] = "Error";
                return RedirectToAction("Index");
            }
        }



    }
}

MVCC.Website/Views/Appointment/Index.cshtml
@model MVCC.Website.Models.AppointmentViewModel
@{
    ViewBag.Title = "Index";
}

<h2>My Appointments</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Patient")
        </th>
        <th>
            @Html.DisplayName("Date")
        </th>
        <th>
            @Html.DisplayName("Time")
        </th>

        <th>
            @Html.DisplayName("Option")
        </th>
    </tr>
    
    @foreach (var item in Model.Appointments)
    {
        <tr>
            <td>@item.Patient.FullName</td>
            <td>@item.AppointmentDate.ToShortDateString()</td>
            <td>@item.AppointmentDate.ToShortTimeString()</td>
            <td>
                @if (!item.IsApproved) { 
                    @Html.ActionLink("Approve", "Approve", "Appointment", new { id = item.Id }, new { @class = "btn btn-primary" })
                }
                 @Html.ActionLink("Set Date", "SetDate", "Appointment", new { id = item.Id }, new { @class = "btn btn-success" })
                @Html.ActionLink("Delete", "", "Appointment", new { id = item.Id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }
</table>

MVCC.Website/Views/Appointment/SetDate.cshtml
@model MVCC.Website.Models.AppointmentSetDateViewModel
@{
    ViewBag.Title = "SetDate";
}

<h2>SetDate</h2>
@using (Html.BeginForm("SetDate", "Appointment", FormMethod.Post))
{
    @Html.Hidden("Id",Model.Id)
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(m => m.Date, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Date, new { @class = "form-control datepicker", Value = "" + Model.Date.ToShortDateString() })
            @Html.ValidationMessageFor(model => model.Date)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Time, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Time, new { @class = "form-control timepicker", Value = "" + Model.Time.ToShortTimeString() })
            @Html.ValidationMessageFor(model => model.Time)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
        </div>
    </div>

}
@section Scripts {
    <script type="text/javascript">
        $(function() { // will trigger when the document is ready
            $('.datepicker')
                .datepicker(
                    {
                        defaultDate: new Date().getDate()
                    }
                ); //Initialise any date pickers

            $('.timepicker').timepicker();
        });
    </script>
}