MVCC.Website/Models/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using MVCC.Model.Entities;

namespace MVCC.Website.Models
{
    public class CategoryIndexViewModel
    {
        public IEnumerable<Category> Categories { get; set; }
    }

    public class CategoryCreateViewModel
    {
        public string CategoryName { get; set; }
    }

    public class CategoryUpdateViewModel
    {
        [Required]
        public Guid Id { get; set; }
        [Required]
        public Category Category { get; set; }
    }
}

MVCC.Website/Controllers/CategoryController.cs
using System;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MVCC.Data.Repositories;
using MVCC.Model.Entities;
using MVCC.Service.Managers;
using MVCC.Website.Attributes;
using MVCC.Website.Models;

namespace MVCC.Website.Controllers
{
    public class CategoryController : Controller
    {
        private readonly CategoryRepository _repository;
        private readonly ApplicationUserManager _manager;
        public CategoryController(CategoryRepository repository, ApplicationUserManager manager)
        {
            _repository = repository;
            _manager = manager;
        }

        [RoleClaimAuthorize(RoleClaim = RoleClaim.CanCreateCategory)]
        public ActionResult Index()
        {
            var model = new CategoryIndexViewModel {Categories = _repository.GetAll()};
            return View(model);
        }


        [HttpGet]
        [RoleClaimAuthorize(RoleClaim = RoleClaim.CanCreateCategory)]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [RoleClaimAuthorize(RoleClaim = RoleClaim.CanCreateCategory)]
        public ActionResult Create(CategoryCreateViewModel model)
        {
            var user = _manager.FindByName(HttpContext.User.Identity.Name);
            if (user == null) return RedirectToAction("Index");
            var cat = new Category {Name = model.CategoryName , CreaterId = user.Id};
            cat.DateCreated = cat.DateUpdated = DateTime.Now;
            if (_repository.Add(cat) != null)
            {
                TempData["Message"] = "Success";
            }
            else
            {
                TempData["Message"] = "Error";
            }
            return RedirectToAction("Index");
        }



        [HttpGet]
        [RoleClaimAuthorize(RoleClaim = RoleClaim.CanDeleteCategory)]
        public ActionResult Update(Guid id)
        {
            var cat = _repository.GetById(id);
            if (cat == null) return RedirectToAction("Index");
            var model = new CategoryUpdateViewModel()
            {
                
                Category = cat
            };

            return View(model);
        }


        [HttpGet]
        [RoleClaimAuthorize(RoleClaim = RoleClaim.CanDeleteCategory)]
        public ActionResult Delete(Guid id)
        {
            var cat = _repository.GetById(id);
            if (cat == null) return RedirectToAction("Index");
            _repository.Delete(cat);
            TempData["Message"] = "Category Deleted";
            return RedirectToAction("Index");
        }


        [HttpPost]
        [RoleClaimAuthorize(RoleClaim = RoleClaim.CanDeleteCategory)]
        public ActionResult Update(Category model)
        {
            if (_repository.Update(model))
            {
                TempData["Message"] = "Success";
            }
            else
            {
                TempData["Message"] = "Error";
            }
            return RedirectToAction("Index");
        }




    }
}

MVCC.Website/Views/Category/Create.cshtml
@model MVCC.Website.Models.CategoryCreateViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm("Create", "Category", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />
    <div class="form-group">
        @Html.LabelFor(m => m.CategoryName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.CategoryName, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryName)
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
        </div>
    </div>

}

MVCC.Website/Views/Category/Index.cshtml
@model MVCC.Website.Models.CategoryIndexViewModel
@{
    ViewBag.Title = "Categories";
}

<h2>Categories</h2>
<h5>Deleting Category will Delete All the Discussions Related to It</h5>
@Html.ActionLink("Create Category","Create",null,new { @class = "btn btn-primary"})
<br/>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Date Created</th>
    </tr>
    @foreach (var item in Model.Categories)
    {
        <tr>
            <th>@item.Name</th>
            <th>@item.DateCreated.ToShortDateString()</th>
            <th>
                @Html.ActionLink("Edit", "Update", new { id = item.Id }, new { @class = "btn btn-info" })
                @Html.ActionLink("Delete","Delete",new { id = item.Id},new { @class = "btn btn-info"})
            </th>
        </tr>
    }
</table>

MVCC.Website/Views/Category/Update.cshtml
@model MVCC.Website.Models.CategoryUpdateViewModel
@{
    ViewBag.Title = "Update";
}

<h2>Update</h2>
@using (Html.BeginForm("Update", "Category", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("Id",Model.Id)
    
    <hr />
    <div class="form-group">
        @Html.LabelFor(m => m.Category.Name, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBox("Name",null, new { @class = "form-control" , Value = Model.Category.Name })
            @Html.ValidationMessageFor(model => model.Category.Name)
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Update" />
        </div>
    </div>

}