MVCC.Website/Models/ForumViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using MVCC.Model.Entities;

namespace MVCC.Website.Models
{
    public class ForumIndexViewModel
    {
        public int PageCount { get; set; }
        public int PageNumber { get; set; }
        public IEnumerable<Model> Models { get; set; }
        public class  Model
        {
            public Category Category { get; set; }
            public int Count { get; set; }
        }
    }

    public class ForumCategoryViewModel
    {
        public int PageCount { get; set; }
        public int PageNumber { get; set; }
        public IEnumerable<Discussion> Discussions { get; set; }
    }

    public class ForumCreateViewModel
    {
        [Required]
        [DisplayName("Enter Topic Name")]
        public string Name { get; set; }
        [Required]
        [DisplayName("Description")]
        public string Description { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateUpdated { get; set; }

        [Required]
        [DisplayName("Select Category")]
        public Guid CategoryId { get; set; }
        public IEnumerable<Category> Categories { get; set; }
    }

    public class DiscussionViewModel
    {
        public Guid Id { get; set; }
        public int Page { get; set; }
        public int PageCount { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime DateCreated { get; set; }
        public string CreaterName { get; set; }
        public string Category { get; set; }
        public IEnumerable<Comment> Comments { get; set; }

        public CommentCreateViewModel CommentCreateViewModel { get; set; }
    }

    public class DiscussionEditViewModel
    {
        [Required]
        public Guid Id { get; set; }

        [Required]
        [DisplayName("Enter Topic Name")]
        public string Name { get; set; }
        [Required]
        [DisplayName("Description")]
        public string Description { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateUpdated { get; set; }

        [Required]
        [DisplayName("Select Category")]
        public Guid CategoryId { get; set; }
        public IEnumerable<Category> Categories { get; set; }
    }
    public class CommentCreateViewModel
    {
        [Required]
        public Guid DiscussionId { get; set; }
        public Guid CommenterId { get; set; }
        [Required]
        public string Context { get; set; }
        public DateTime DateCommented { get; set; }

    }
}

MVCC.Website/Controllers/ForumController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MVCC.Data.Repositories;
using MVCC.Model.Entities;
using MVCC.Web.Shared.Extensions;
using MVCC.Website.Models;
using PagedList;
namespace MVCC.Website.Controllers
{
    public class ForumController : Controller
    {
        private readonly CategoryRepository _repository;
        private readonly DiscussionRepository _discussionRepository;
        private readonly CategoryRepository _categoryRepository;
        private readonly CommentRepository _commentRepository;
        public ForumController(CategoryRepository repository, DiscussionRepository discussionRepository, CategoryRepository categoryRepository, CommentRepository commentRepository)
        {
            _repository = repository;
            _discussionRepository = discussionRepository;
            _categoryRepository = categoryRepository;
            _commentRepository = commentRepository;
        }
        // GET: Forum
        public ActionResult Index(int? page)
        {
            page = page ?? 1;

            var model = new ForumIndexViewModel();
            var list = _repository.GetAll();
            var temp = list.Select(category => new ForumIndexViewModel.Model()
            {
                Category = category, Count = _discussionRepository.CountByCategory(category)
            }).ToList();
            model.Models = temp.ToPagedList(page.Value,30);
            return View(model);
        }


        public ActionResult ForumCategory(Guid id,int? page)
        {
            var model = new ForumCategoryViewModel
            {
                PageNumber = page ?? 1,
                PageCount = _discussionRepository.Pages(30)
            };
            model.Discussions = _discussionRepository.GetByCategory(id).ToPagedList(model.PageNumber,30);
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var model = new ForumCreateViewModel()
            {
                Categories = _categoryRepository.GetAll()
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(ForumCreateViewModel model)
        {
            var discussion = new Discussion()
            {
                CategoryId = model.CategoryId,
                CreaterId = User.Identity.GetGuidUserId(),
                DateCreated = DateTime.Now,
                DateUpdated = DateTime.Now,
                Description = model.Description,
                Name = model.Name
            };
            var disc = _discussionRepository.Add(discussion);
            if (disc != null)
            {
                TempData["Message"] = "Success";
                return RedirectToAction("Discussion",new { id = disc.Id});
            }
            TempData["Message"] = "Error";
            return View(model);
        }

        public ActionResult Discussion(Guid id,int? page)
        {
            var discussion = _discussionRepository.GetById(id);
            if (discussion == null)
            {
                TempData["Message"] = "Error";
                return RedirectToAction("Index");
            }

            var model = new DiscussionViewModel
            {
                Id = id,
                Page = page ?? 1,
                Name = discussion.Name,
                Description = discussion.Description,
                CreaterName = discussion.Creater.Name,
                DateCreated = discussion.DateCreated,
                Category = discussion.Category.Name,
                PageCount = _commentRepository.GetCountByDiscussion(id, 20),
            };
            model.Comments = _commentRepository.GetByDiscussion(id, model.Page, 20);
            return View(model);

        }

        public ActionResult Edit(Guid id)
        {
            var discussion = _discussionRepository.GetById(id);
            if (discussion.CreaterId.ToString() == HttpContext.User.Identity.GetUserId() || HttpContext.User.IsInRole("Admin"))
            {
                var model = new DiscussionEditViewModel()
                {
                    Id = id,
                    CategoryId = discussion.CategoryId,
                    Name = discussion.Name,
                    Description = discussion.Description,
                    Categories = _categoryRepository.GetAll()
                };
                return View(model);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Update(DiscussionEditViewModel model)
        {
            var discussion = new Discussion()
            {
                Id = model.Id,
                CategoryId = model.CategoryId,
                Name = model.Name,
                Description = model.Description
            };

            var check = _discussionRepository.Update(discussion);
            if (check)
            {
                TempData["Message"] = "Success";
                return RedirectToAction("Index", new {id = model.Id});
            }
            TempData["Message"] = "Failed";
            return RedirectToAction("Discussions","Profile");
        }

        public ActionResult Delete(Guid id)
        {
            var discussion = _discussionRepository.GetById(id);
            if (discussion.CreaterId.ToString() == HttpContext.User.Identity.GetUserId() || HttpContext.User.IsInRole("Admin"))
            {
                _discussionRepository.Delete(discussion);
                TempData["Message"] = "Success";
                return RedirectToAction("Discussion","Profile");
            }
            TempData["Message"] = "Error";
            return RedirectToAction("Discussion","Profile");

        }

        [HttpPost]
        public ActionResult Comment(CommentCreateViewModel model)
        {
            var comment = new Comment()
            {
                Context = model.Context,
                CommentedDate = DateTime.Now,
                CommenterId = User.Identity.GetGuidUserId(),
                DiscussionId = model.DiscussionId
            };

            var com = _commentRepository.Add(comment);
            if (com != null)
            {
                return RedirectToAction("Discussion",
                    new
                    {
                        id = model.DiscussionId,
                        page = _commentRepository.GetCountByDiscussion(model.DiscussionId, 20)
                    });
            }
            TempData["Message"] = "Error";
            return RedirectToAction("Discussion", new {id = model.DiscussionId});
        }

    }
}

MVCC.Website/Views/Forum/Create.cshtml
@model MVCC.Website.Models.ForumCreateViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create Discussion</h2>

@using (Html.BeginForm("Create","Forum",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryId, new SelectList(Model.Categories, "Id", "Name"), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVCC.Website/Views/Forum/Discussion.cshtml
@using System.Web.UI.WebControls
@using PagedList
@using PagedList.Mvc
@model MVCC.Website.Models.DiscussionViewModel
@{
    ViewBag.Title = "Discussion";
}

<h2>Discussion : @Model.Name</h2>
<div class="container">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="left">
                @Model.CreaterName : @Model.DateCreated.ToShortDateString()
            </div>
        </div>
        <div class="panel-body">
            @Model.Description
        </div>
    </div>
</div>
<br/>
Page @(Model.PageCount < Model.Page ? 0 : Model.Page) of @Model.PageCount
<div class="container">
    @foreach (var item in Model.Comments)
    {
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="left">
                    @item.Commenter.Name : @item.CommentedDate.ToShortDateString()
                </div>
            </div>
            <div class="panel-body">
                @item.Context
            </div>
        </div>
    }
</div>

@if(Request.IsAuthenticated)
{
    <div class="container">
        <div class="panel panel-body">
            @using (Html.BeginForm("Comment", "Forum", FormMethod.Post))
            {
                @Html.Hidden("DiscussionId", @Model.Id)
                
                @Html.TextArea("Context", new { @class = "form-control", PlaceHolder = "Enter Your Comment" })
                <br />
                <button type="submit" class="btn btn-primary">Comment</button>
            }
        </div>
    </div>
}

@Html.PagedListPager((IPagedList)Model.Comments, page => Url.Action("Discussion",
   new { page, id = Model.Id }))

MVCC.Website/Views/Forum/Edit.cshtml
@model MVCC.Website.Models.DiscussionEditViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit Discussion</h2>

@using (Html.BeginForm("Update","Forum",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("Id",Model.Id);
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", Value = Model.Name }  })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2", Value = Model.Description })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryId, new SelectList(Model.Categories, "Id", "Name"), new { htmlAttributes = new { @class = "form-control",Value = Model.CategoryId } })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Board", "Discussion","Profile")
</div>

MVCC.Website/Views/Forum/ForumCategory.cshtml
@using PagedList
@using PagedList.Mvc
@model MVCC.Website.Models.ForumCategoryViewModel
@{
    ViewBag.Title = "ForumCategory";
}

<h2>ForumCategory</h2>

@Html.ActionLink("Create Discussion","Create","Forum",null, new { @class = "btn btn-primary" })
<br/>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
<table class="table">
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Created By</th>
        <th>Date Created</th>
    </tr>
    @foreach (var item in Model.Discussions)
    {
        <tr>
            <td>@Html.ActionLink(item.Name,"Discussion",new { id = item.Id })</td>
            <td>
                @(item.Description.Length > 30 ? item.Description.Substring(0,27) + "..." : item.Description)
            </td>
            <td>
                @item.Creater.FullName
            </td>
            <td>@item.DateCreated</td>
        </tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model.Discussions, page => Url.Action("Index",new { page }))

MVCC.Website/Views/Forum/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model MVCC.Website.Models.ForumIndexViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Forums</h2>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
<table class="table">
    <tr>
        <th>Category</th>
        <th>Date Created</th>
        <th>Post Count</th>
    </tr>
    @foreach (var item in Model.Models)
    {
        <tr>
            <th>@Html.ActionLink(item.Category.Name,"ForumCategory","Forum",new { Id = item.Category.Id },new { @class = "link" })</th>
            <th>@item.Category.DateCreated.ToShortDateString()</th>
            <th>@item.Count</th>
        </tr>
    }
</table>
@Html.PagedListPager((IPagedList) Model.Models, page => Url.Action("Index",
    new { page }))