MVCC.Website/Models/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using MVCC.Model.Entities;

namespace MVCC.Website.Models
{
    public class EventViewModel
    {
       public IEnumerable<Event> Events { get; set; }
    }
    public class EventRegsiterViewModel
    {
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Event Name")]
        public string Name { get; set; }


        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 15)]
        [DataType(DataType.Text)]
        [Display(Name = "Event Description")]
        public string Description { get; set; }


        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Address of Event")]
        public string Location { get; set; }



        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Date of Event")]
        public DateTime DateofEvent { get; set; }

        
        [DataType(DataType.Date)]
        public DateTime DateCreated;

        public EventRegsiterViewModel()
        {
            DateCreated = DateTime.Today;
        }
    }

    public class EventUpdateViewModel
    {
        [Required]
        public Guid Id { get; set; }

        [Required]
        [Display(Name = "Event Name")]
        public string Name { get; set; }


        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 15)]
        [Display(Name = "Event Description")]
        public string Description { get; set; }


        [Required]
        [Display(Name = "Location/Address of Event")]
        public string Location { get; set; }



        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Date of Event of Event")]
        public DateTime DateofEvent { get; set; }


        [DataType(DataType.Date)]
        public DateTime DateUpdated;

    }
}

MVCC.Website/Controllers/EventController.cs
using System;
using System.Web.Mvc;
using MVCC.Data.Repositories;
using MVCC.Model.Entities;
using MVCC.Website.Models;

namespace MVCC.Website.Controllers
{
    public class EventController : Controller
    {
        private readonly EventRepository _eventRepository;
        public EventController(EventRepository repository)
        {
            _eventRepository = repository;
        }
        // GET: Event
        [HttpGet]
        public ActionResult Index()
        {
            var list = _eventRepository.GetAll();
            EventViewModel model = new EventViewModel()
            {
                Events = list
            };
            return View(model);
        }

        [HttpGet]
        [ActionName("Create")]

        public ActionResult Create()
        {
            return View(new EventRegsiterViewModel());
        }



        [HttpPost]
        [ActionName("Create")]

        public ActionResult Create(EventRegsiterViewModel rmodel)
        {
            var model = new Event()
            {
                Name = rmodel.Name,
                DateCreated = DateTime.Now,
                DateUpdated = DateTime.Now,
                DateofEvent = rmodel.DateofEvent,
                Description = rmodel.Description,
                Location = rmodel.Location

            };

            if (_eventRepository.Add(model) != null)
            {
                TempData["Message"] = "Success";
                return RedirectToAction("Index");
            }
            TempData["Message"] = "Error in Input";
            return View(model);
        }

        [HttpGet]
        [ActionName("Update")]
        public ActionResult Update(Guid id)
        {
            var model = _eventRepository.GetById(id);
            if (model != null)
            {
                EventUpdateViewModel Model = new EventUpdateViewModel()
                {
                    Name = model.Name,
                    DateofEvent = model.DateofEvent,
                    Id = model.Id,
                    Description = model.Description,
                    Location = model.Location
                };
                return View(Model);
            }
            TempData["Message"] = "Error Not Found";
            return RedirectToAction("Index");
        }

        [HttpGet]
        [ActionName("Delete")]
        public ActionResult Delete(Guid id)
        {

            var model = _eventRepository.GetById(id);
            if (model != null)
            {
                _eventRepository.Delete(m => m.Id == model.Id);
                TempData["Message"] = "Successfully Deleted";
                return RedirectToAction("Index");
            }
            TempData["Message"] = "Error Not Found";
            return RedirectToAction("Index");
        }


        [HttpPost]
        [ActionName("Update")]
        public ActionResult Update(EventUpdateViewModel model)
        {
            model.DateUpdated = DateTime.Now;
            var Model = new Event()
            {
                Id = model.Id,
                DateUpdated = model.DateUpdated,
                DateofEvent = model.DateofEvent,
                Description = model.Description,
                Name = model.Name,
                Location = model.Location
            };
            if (_eventRepository.Update(Model))
            {
                TempData["Message"] = "Error Updating";
            }
            else
            {
                TempData["Message"] = "Updated";
            }
            return RedirectToAction("Index");
        }


    }
}

MVCC.Website/Views/Event/Create.cshtml
@model MVCC.Website.Models.EventRegsiterViewModel
@{
    ViewBag.Title = "Create Event";
}

<h2>Create Event</h2>

@using (Html.BeginForm("Create", "Event", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.DateCreated)
    <hr />
    
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Name)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Description)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Location, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Location, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Location)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.DateofEvent, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.DateofEvent, new { @class = "form-control datepicker" , Value = "" + DateTime.Today.ToShortDateString() })
            @Html.ValidationMessageFor(model => model.DateofEvent)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
        </div>
    </div>

}

@section Scripts {
<script type="text/javascript">
    $(function () { // will trigger when the document is ready
        $('.datepicker').datepicker(
            {
                    defaultDate: new Date().getDate()
            }
        ); //Initialise any date pickers
    });
</script>

}

MVCC.Website/Views/Event/Index.cshtml
@model MVCC.Website.Models.EventViewModel
@{
    ViewBag.Title = "Event Info Page";
}

<h2>Events</h2>
<div>
    @Html.ActionLink("Create Event", "Create", null, new { @class = "btn btn-primary" })
</div>
<br/>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Location</th>
        <th>Time of Event</th>
        <th>Options</th>
    </tr>
    @foreach (var item in Model.Events)
    {
        <tr>
            <td>@(item.Name)</td>
            <td>@(item.Description)</td>
            <td>@(item.Location)</td>
            <td>@(item.DateofEvent.ToShortDateString())</td>
            <td>
                @Html.ActionLink("Update", "Update", new { id = item.Id}, new { @class = "btn btn-success" })
                @Html.ActionLink("Delete", "Delete", new { id = item.Id}, new { @class = "btn btn-danger" })

            </td>
            
        </tr>
    }
</table>

MVCC.Website/Views/Event/Update.cshtml
@model MVCC.Website.Models.EventUpdateViewModel
@{
    ViewBag.Title = "Update";
}

<h2>Update</h2>

@using (Html.BeginForm("Update", "Event", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />

    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", Value = Model.Name })
            @Html.ValidationMessageFor(model => model.Name)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Description, new { @class = "form-control", Value = Model.Description })
            @Html.ValidationMessageFor(model => model.Description)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Location, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Location, new { @class = "form-control", Value = Model.Location })
            @Html.ValidationMessageFor(model => model.Location)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.DateofEvent, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.DateofEvent, new { @class = "form-control datepicker", Value = Model.DateofEvent.ToShortDateString() })
            @Html.ValidationMessageFor(model => model.DateofEvent)
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
        </div>
    </div>
}

@section Scripts {
    <script type="text/javascript">
    $(function () { // will trigger when the document is ready
        $('.datepicker').datepicker(
            {
//                    defaultDate: new Date().getDate()
            }
        ); //Initialise any date pickers
    });
    </script>

}